name: Check ENV
on:
  workflow_dispatch:

env:
  NAME: my_name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: 'Check helm'
      run: |
        helm version

    - name: 'Check env vars'
      run: |
        echo "this is my name: " ${{ env.NAME }}
