name: Check ENV
on:
  workflow_dispatch:

env:
  NAME: my_name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: 'Check helm'
      run: |
        helm version

    - name: 'Check env vars'
      run: |
        echo "this is my name: " ${{ env.NAME }}

    - name: 'Dummy Step'
      id: condition_1
      continue-on-error: true
      run: blablabla


    - name: 'Check 1st condition'
      id: condition_2
      continue-on-error: true
      if: steps.condition_1.outcome=='failure'
      run: blablabla

    - name: 'Check 2nd condition'
      if: steps.condition_1.outcome=='failure' && steps.condition_2.outcome=='success'
      run: echo "awesome!"
